# URL do cliente REST
quarkus.rest-client.rawg-api.url=https://api.rawg.io/api
quarkus.rest-client.rawg-api.connect-timeout=2
quarkus.rest-client.rawg-api.read-timeout=2000

# Sua chave da RAWG
rawg.api-key=yourapikey
rawg.max-attempts=3
rawg.retry-delay=2000
