#-----------------------------------------------------------------------------------------------------------------------
# API RAWG
#-----------------------------------------------------------------------------------------------------------------------

# URL do cliente REST
quarkus.rest-client.rawg-api.url=https://api.rawg.io/api
quarkus.rest-client.rawg-api.connect-timeout=3000
quarkus.rest-client.rawg-api.read-timeout=3000


# A sua chave da RAWG
rawg.api-key=yourapikey
# Máximo de tentativas de retry em timeout.
rawg.max-attempts=3
# Delay a cada tentativa de retry
rawg.retry-delay=3000

#-----------------------------------------------------------------------------------------------------------------------
# API CheapShark
#-----------------------------------------------------------------------------------------------------------------------

quarkus.rest-client.cheapshark-api.url=https://www.cheapshark.com/api/1.0/

# Máximo de tentativas de retry em timeout.
cheapshark.max-attempts=3
# Delay a cada tentativa de retry
cheapshark.retry-delay=3000
