# URL do cliente REST
quarkus.rest-client.rawg-api.url=https://api.rawg.io/api
quarkus.rest-client.rawg-api.connect-timeout=2000
quarkus.rest-client.rawg-api.read-timeout=2000

# A sua chave da RAWG
rawg.api-key=yourapikey
# Máximo de tentativas de retry em timeout.
rawg.max-attempts=3
# Delay a cada tentativa de retry
rawg.retry-delay=2000
